oslopride/oslopride-website

.vscode/extensions.json
README.md

Setup and workflow doc

---

pages/contact/index.jsx
store/contact/index.js
store/reducer.js
store/saga.js

Contact page

---

components/Button/index.jsx
components/Header/index.jsx
components/Header/navigation.jsx
components/Hero/index.jsx
components/Link/index.jsx
pages/_app.jsx
pages/about/index.jsx
pages/index.jsx
pages/pride-art/index.jsx
pages/pride-house/index.jsx
pages/pride-parade/index.jsx
pages/pride-park/index.jsx
pages/pride-store/index.jsx
pages/program/index.jsx
utils/theme.js

Color theme

---

components/Header/index.jsx

fix date color

---

.eslintrc
.vscode/settings.json
components/ArticlePreview/hooks.js
components/ArticlePreview/index.jsx
components/SanityBlockContent/index.jsx
pages/index.jsx
store/articles/index.js
store/front-page/index.js

Featured articles on front page

---

components/FeaturedCallToActionList/index.jsx

add call to action icons

---

components/SanityBlockContent/index.jsx

set max width on images inside block content

---

components/Button/index.jsx
components/Header/index.jsx
components/Header/navigation.jsx
components/SanityBlockContent/index.jsx

Add css-transitions to header navigation reveal

---

components/FeaturedPartners/index.jsx
pages/index.jsx

Added partners to frontpage
Fix #49

Frontpage partners

---

components/Footer/index.jsx
components/Header/navigation.jsx

Remove interpride agm

---

pages/pride-art/index.jsx
pages/pride-house/index.jsx
pages/pride-parade/index.jsx
pages/pride-park/index.jsx
store/pride-art/index.js
store/pride-house/index.js
store/pride-parade/index.js
store/pride-park/index.js

Featured articles on landing pages

---

components/FeaturedPartners/index.jsx
components/Footer/index.jsx
pages/_app.jsx
pages/partners/index.jsx

Fixed small style issues
- #74 
- same margin to footer on bottom as on top to header

Small fixes

---

components/FeaturedPartners/index.jsx
pages/partners/index.jsx

Changed featured partner to render null if empty

---

components/Header/index.jsx
package.json
pages/_app.jsx
utils/google-analytics.js
yarn.lock

Google analytics

---

components/Footer/index.jsx

add cookie policy to footer

---

pages/event/index.jsx

add centered image to event page

---

components/Header/navigation.jsx
pages/events/index.jsx
store/saga.js

Venues where not initialized when navigating to program client-side/non-ssr, throwing an exception.
Also add back the reverted "add link to mainmenu"

Tiny patch for initialization-bug when navigating to program

---

components/SanityBlockContent/index.jsx
components/SanityBlockContentSerializers/index.jsx
components/YouTubeEmbed/index.jsx
package.json
yarn.lock

Add support for YouTube embed in body of articles and pages

---

components/EventList/index.jsx

remove display of external arena

---

components/EventList/index.jsx
store/events/index.js

Improve event sort

---

components/EventList/index.jsx
package.json
yarn.lock

Lazy loading
